### ISSUE TITLE
底层存储用的是二进制树吗？

### ISSUE THREAD

**Issue by csh0101** [metowolf/iplist#10]

**Comment by metowolf** [comment]
ipdb 存储用的二进制树

**Comment by csh0101** [comment]
> ipdb 存储用的二进制树

果然....我最近也在研究ipip库的存储，感觉ipip库的索引数据有些大，在优化方面您有什么好的思路吗，如果不介意的话可以分享一下。otherwise，二进制树的优点到底在哪儿😂，我想它可能对ipv6数据比较友好。。如果您有整理地理信息规范的渠道 譬如ipip库的标准、iso-3661的标准，请联系我。

**Comment by csh0101** [comment]
感觉可以优化最短的索引，这样就能减少索引的大小了。。

**Comment by metowolf** [comment]
一个建议是参考 MaxMind mmdb 做法，索引区采用自适应长度而非固定 4 字节。
另一个是可以对内容区整体走一次压缩，或者将国家、省市字段拆开做一下字典合并。

**Comment by csh0101** [comment]
感谢，我想我该去搜索一些MaxMind mmdb的做法。
