### ISSUE TITLE
缺少  克孜勒苏柯尔克孜自治州 的数据

### ISSUE THREAD

**Issue by taills** [metowolf/iplist#11]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/47925925/166870701-2d6fec2c-7d7a-4c72-8d4c-7612f06506db.png">

https://raw.githubusercontent.com/metowolf/iplist/master/data/cncity/653000.txt 不存在哟

**Comment by metowolf** [comment]
已更换 OpenIPDB 源，数据修复了，感谢反馈。
