### ISSUE TITLE
请问本数据库更新频率较低的主要原因是什么？

### ISSUE THREAD

**Issue by UptonEdward** [metowolf/iplist#12]

**Comment by metowolf** [comment]
当前纯真数据库版本停留在 2022.04.27 未能获取到更新，这里会考虑更换数据源。

**Comment by metowolf** [comment]
https://github.com/out0fmemory/qqwry.dat/issues/11

**Comment by fos236** [comment]
纯真官方公众号开放的有最新社区版IP库,平均两周更新一次，v20230308离线版：https://www.cz88.net/soft/f66y2F-2023-03-08.zip

**Comment by metowolf** [comment]
@fos236 感谢，目前已重新恢复与上游的同步。
