### ISSUE TITLE
大陆ip段缺少1.18.128.0/24

### ISSUE THREAD

**Issue by l4326769** [metowolf/iplist#14]
1.18.128.0/24段为北京ip段

**Comment by metowolf** [comment]
根据纯真数据，解析结果为「韩国」。
可以考虑向上游 https://www.cz88.net/review 进行反馈。

**Comment by metowolf** [comment]
根据相关信息，OpenIPDB 已修正条目，感谢反馈
https://github.com/metowolf/iplist/blob/554cfc29968bff35d300828ece9649c9a8d8a89f/data/special/china.txt#L35
